# 넘파이 배열
- 파이썬에서 배열을 사용하기 위한 표준 패키지, 수치해석용 파이썬 패키지

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\users\shoseo\appdata\local\programs\python\python38\python.exe -m pip install --upgrade pip' command.


In [3]:
import numpy as np

### 1차원 배열

In [4]:
ar = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
type(ar)

numpy.ndarray

### 벡터화 연산
- 배열의 각 원소에 대한 반복 연산을 하나의 명령어로 처리함.

In [7]:
# 일반적으로 for 반복문 사용
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
answer = []
for di in data:
    answer.append(2 * di)
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [9]:
# 벡터화 연산 사용
x = np.array(data)
x * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
# 일반적인 리스트 객체
L = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(2 * L)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


### 2차원 배열

In [11]:
c = np.array([[0, 1, 2], [3, 4, 5]])  # 2 x 3 array
c

array([[0, 1, 2],
       [3, 4, 5]])

In [12]:
# 행의 갯수
len(c)

2

In [13]:
# 열의 갯수
len(c[0])

3

### 3차원 배열

In [14]:
d = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]])   # 2 x 3 x 4 array

In [15]:
len(d), len(d[0]), len(d[0][0])

(2, 3, 4)

### 배열의 차원과 크기 알아내기
- ndim : 배열의 차원 / shape : 배열의 크기

In [16]:
# c = np.array([[0, 1, 2], [3, 4, 5]])
print(c.ndim)
print(c.shape)

2
(2, 3)


### 배열 슬라이싱

In [17]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [18]:
a[0, :]  # 첫번째 행 전체

array([0, 1, 2, 3])

In [19]:
a[:, 1]  # 두번째 열 전체

array([1, 5])

In [21]:
a[1, 1:]  # 두번째 행의 두번째 열부터 끝열까지

array([5, 6, 7])

### 전치 연산
- 행과 열을 바꾸는 작업

In [22]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### 배열의 크기 변형 (reshape)

In [24]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
b = a.reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

- 다차원 배열을 1차원으로 만들기 위해서는 flatten 또는 ravel 메서드 사용

In [26]:
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### 난수 발생
- 시드 설정 
- rand: 0부터 1사이의 균일 분포
- randn: 표준 정규 분포
- randint: 균일 분포의 정수 난수

In [31]:
np.random.seed(2021)
np.random.rand(5)

array([0.60597828, 0.73336936, 0.13894716, 0.31267308, 0.99724328])

In [32]:
np.random.randn(5)

array([-0.17383896, -0.20136597,  0.77039766,  1.20160669, -0.19009954])

In [34]:
np.random.randint(5, size=5)

array([1, 4, 2, 2, 0])